-- Run once in Snowsight. Replace <YOUR_USER> with your Snowflake username.
-- Gives dbt its own role: read RAW, write CLEANED and BUSINESS_READY, nothing else.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;

GRANT USAGE ON DATABASE BANKING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA BANKING.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BANKING.RAW TO ROLE TRANSFORMER;

CREATE SCHEMA IF NOT EXISTS BANKING.CLEANED;
CREATE SCHEMA IF NOT EXISTS BANKING.BUSINESS_READY;
GRANT ALL ON SCHEMA BANKING.CLEANED TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA BANKING.BUSINESS_READY TO ROLE TRANSFORMER;

-- Keep the double quotes: a name starting with a digit (e.g. "7Z1Q1") is invalid without them.
GRANT ROLE TRANSFORMER TO USER "<YOUR_USER>";
