-- Run once in Snowsight. Replace <YOUR_USER> with your Snowflake username (keep the double quotes).
-- LOADER is the role Airflow uses for COPY INTO: it can only load into RAW.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE BANKING TO ROLE LOADER;
GRANT USAGE ON SCHEMA BANKING.RAW TO ROLE LOADER;
GRANT USAGE ON STAGE BANKING.RAW.s3_stage TO ROLE LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA BANKING.RAW TO ROLE LOADER;

GRANT ROLE LOADER TO USER "<YOUR_USER>";
