-- Run once in Snowsight. Replace <YOUR_USER> with your Snowflake username (keep the double quotes).
-- BI_READER is the role Power BI connects with: read-only, BUSINESS_READY schema only.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS BI_READER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE BI_READER;
GRANT USAGE ON DATABASE BANKING TO ROLE BI_READER;
GRANT USAGE ON SCHEMA BANKING.BUSINESS_READY TO ROLE BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA BANKING.BUSINESS_READY TO ROLE BI_READER;
-- dbt rebuilds the tables with CREATE OR REPLACE; future grants re-apply to each rebuilt table.
GRANT SELECT ON FUTURE TABLES IN SCHEMA BANKING.BUSINESS_READY TO ROLE BI_READER;

GRANT ROLE BI_READER TO USER "<YOUR_USER>";
